SET LINESIZE 150
SET PAGESIZE 50
SET FEEDBACK OFF
SET VERIFY OFF
SET TRIMSPOOL ON
SET HEADING ON

PROMPT ==============================
PROMPT STATUS DATABASE
PROMPT ==============================
COLUMN name FORMAT A10
COLUMN open_mode FORMAT A20
COLUMN database_role FORMAT A15

SELECT name, open_mode, database_role
FROM v$database;

PROMPT
PROMPT ==============================
PROMPT STATUS REPLIKASI ARCHIVE LOG
PROMPT ==============================
ALTER SESSION SET NLS_DATE_FORMAT='DD-MM-YYYY HH24:MI:SS';

COLUMN thread# FORMAT 999
COLUMN last_seq FORMAT 999999
COLUMN applied_seq FORMAT 999999
COLUMN last_app_timestamp FORMAT A20
COLUMN arc_diff FORMAT 999

SELECT
    A.THREAD# AS "THREAD#",
    B.LAST_SEQ AS "LAST_SEQ",
    A.APPLIED_SEQ AS "APPLIED_SEQ",
    TO_CHAR(A.LAST_APP_TIMESTAMP,'DD-MM-YYYY HH24:MI:SS') AS "LAST_APP_TIMESTAMP",
    B.LAST_SEQ - A.APPLIED_SEQ AS "ARC_DIFF"
FROM
    (
        SELECT THREAD#, MAX(SEQUENCE#) AS APPLIED_SEQ, MAX(NEXT_TIME) AS LAST_APP_TIMESTAMP
        FROM GV$ARCHIVED_LOG
        WHERE APPLIED='YES' OR APPLIED='ÍN-MEMORY'
        GROUP BY THREAD#
    ) A,
    (
        SELECT THREAD#, MAX(SEQUENCE#) AS LAST_SEQ
        FROM GV$ARCHIVED_LOG
        GROUP BY THREAD#
    ) B
WHERE A.THREAD# = B.THREAD#;

PROMPT
PROMPT ==============================
PROMPT STATUS SWITCHOVER / ROLE CHANGE
PROMPT ==============================
COLUMN database_role FORMAT A15
COLUMN open_mode FORMAT A15
COLUMN protection_mode FORMAT A25
COLUMN protection_level FORMAT A25
COLUMN switchover_status FORMAT A20

SELECT
    DATABASE_ROLE,
    OPEN_MODE,
    PROTECTION_MODE,
    PROTECTION_LEVEL,
    SWITCHOVER_STATUS
FROM V$DATABASE;

